services:
  render:
    build:
      context: ./
      dockerfile: ./cmd/render/Dockerfile
    image: ayjchen/cc-exercise-3:render
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3031:3031"
  
  get:
    build:
      context: ./
      dockerfile: ./cmd/get/Dockerfile
    image: ayjchen/cc-exercise-3:get
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3032:3032"
  
  post:
    build:
      context: ./
      dockerfile: ./cmd/post/Dockerfile
    image: ayjchen/cc-exercise-3:post
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3033:3033"

  update:
    build:
      context: ./
      dockerfile: ./cmd/update/Dockerfile
    image: ayjchen/cc-exercise-3:update
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3034:3034"
    
  delete:
    build:
      context: ./
      dockerfile: ./cmd/delete/Dockerfile
    image: ayjchen/cc-exercise-3:delete
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3035:3035"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"

  nginx:
    image: nginx:1.19.0
    ports:
      - "3030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "render"
      - "get"
      - "post"
      - "update"
      - "delete"